/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programaritmatika;

/**
 *
 * @author Mahendra
 */
public class NewJFrame extends javax.swing.JFrame {
    String jenis = "";
    
    
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jenarit = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        jumbil = new javax.swing.JComboBox<String>();
        bill4 = new javax.swing.JLabel();
        bil1 = new javax.swing.JTextField();
        bil2 = new javax.swing.JTextField();
        bil3 = new javax.swing.JTextField();
        bil4 = new javax.swing.JTextField();
        bill1 = new javax.swing.JLabel();
        bill2 = new javax.swing.JLabel();
        bill3 = new javax.swing.JLabel();
        ket = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        keter = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        kete = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();
        label6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("PROGRAM ARITMATIKA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 10, 120, 14);

        jLabel2.setText("Jenis Aritmatika");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 40, 110, 14);

        jenarit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Pilih Salah Satu ---", "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian" }));
        jenarit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenaritActionPerformed(evt);
            }
        });
        getContentPane().add(jenarit);
        jenarit.setBounds(130, 40, 230, 20);

        jLabel3.setText("Jumlah Bilangan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 80, 100, 14);

        jumbil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Pilih Salah Satu ---", "2", "3", "4" }));
        jumbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumbilActionPerformed(evt);
            }
        });
        getContentPane().add(jumbil);
        jumbil.setBounds(130, 80, 230, 20);

        bill4.setText("Bilangan 4");
        getContentPane().add(bill4);
        bill4.setBounds(30, 200, 60, 14);

        bil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil1ActionPerformed(evt);
            }
        });
        getContentPane().add(bil1);
        bil1.setBounds(130, 110, 230, 30);
        getContentPane().add(bil2);
        bil2.setBounds(130, 140, 230, 30);
        getContentPane().add(bil3);
        bil3.setBounds(130, 170, 230, 30);
        getContentPane().add(bil4);
        bil4.setBounds(130, 200, 230, 30);

        bill1.setText("Bilangan 1");
        getContentPane().add(bill1);
        bill1.setBounds(30, 110, 60, 14);

        bill2.setText("Bilangan 2");
        getContentPane().add(bill2);
        bill2.setBounds(30, 140, 60, 14);

        bill3.setText("Bilangan 3");
        getContentPane().add(bill3);
        bill3.setBounds(30, 170, 60, 14);

        ket.setBorder(javax.swing.BorderFactory.createTitledBorder("OPERASI"));
        ket.setLayout(null);
        ket.add(jLabel4);
        jLabel4.setBounds(16, 220, 0, 0);
        ket.add(jLabel5);
        jLabel5.setBounds(25, 220, 0, 0);
        ket.add(keter);
        keter.setBounds(25, 232, 0, 0);

        jButton1.setText("PROSES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ket.add(jButton1);
        jButton1.setBounds(120, 180, 230, 30);
        ket.add(kete);
        kete.setBounds(20, 230, 0, 0);

        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane1.setViewportView(hasil);

        ket.add(jScrollPane1);
        jScrollPane1.setBounds(120, 210, 230, 96);
        ket.add(label6);
        label6.setBounds(14, 220, 100, 20);

        getContentPane().add(ket);
        ket.setBounds(10, 60, 370, 320);

        setBounds(0, 0, 413, 446);
    }// </editor-fold>//GEN-END:initComponents

    private void jumbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumbilActionPerformed
    if(jumbil.getSelectedItem().equals("2")){
           bil1.show(true);bill1.show(true);
           bil2.show(true);bill2.show(true);
           bil3.show(false);bill3.show(false);
           bil4.show(false);bill4.show(false);}
    if(jumbil.getSelectedItem().equals("3")){
           bil1.show(true);bill1.show(true);
           bil2.show(true);bill2.show(true);
           bil3.show(true);bill3.show(true);
           bil4.show(false);bill4.show(false);}
    if(jumbil.getSelectedItem().equals("4")){
           bil1.show(true);bill1.show(true);
           bil2.show(true);bill2.show(true);
           bil3.show(true);bill3.show(true);
           bil4.show(true);bill4.show(true);}
    }//GEN-LAST:event_jumbilActionPerformed

    private void bil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bil1ActionPerformed

    private void jenaritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenaritActionPerformed
    if(jenarit.getSelectedItem().equals("Penjumlahan")){
           jenis = "Penjumlahan";
           label6.setText("Penjumlahan : ");
        }
    if(jenarit.getSelectedItem().equals("Pengurangan")){
           jenis = "Pengurangan";
           label6.setText("Pengurangan : ");
        }
    if(jenarit.getSelectedItem().equals("Perkalian")){
           jenis = "Perkalian";
           label6.setText("Perkalian : ");
        }
    if(jenarit.getSelectedItem().equals("Pembagian")){
           jenis = "Pembagian";
           label6.setText("Pembagian : ");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jenaritActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
    double hasil1;
    
        if(jenarit.getSelectedItem().equals("Pengurangan")){
           if (jumbil.getSelectedItem().equals("2")){
           double a = Double.parseDouble(bil1.getText());
           double b = Double.parseDouble(bil2.getText());
           hasil1 = a-b;
           hasil.setText(a + " - " + b + " = " + hasil1 );
           }
           else if (jumbil.getSelectedItem().equals("3")){
           double a = Double.parseDouble(bil1.getText());
           double b = Double.parseDouble(bil2.getText());
           double c = Double.parseDouble(bil3.getText());
           hasil1 = a-b-c;
           hasil.setText(a + " - " + b +" - "+ c +" = " + hasil1 );
           }
           else if (jumbil.getSelectedItem().equals("4")){
           double a = Double.parseDouble(bil1.getText());
           double b = Double.parseDouble(bil2.getText());
           double c = Double.parseDouble(bil3.getText());
           double d = Double.parseDouble(bil4.getText());
           hasil1 = a-b-c-d;
           hasil.setText(a + " - " + b +" - "+ c +" - "+ d+" = " + hasil1 );
           }     
        }
        else if(jenarit.getSelectedItem().equals("Penjumlahan")){
           if (jumbil.getSelectedItem().equals("2")){
           double a = Double.parseDouble(bil1.getText());
           double b = Double.parseDouble(bil2.getText());
           hasil1 = a+b;
           hasil.setText(a + " + " + b + " = " + hasil1 );
           }
           else if (jumbil.getSelectedItem().equals("3")){
           double a = Double.parseDouble(bil1.getText());
           double b = Double.parseDouble(bil2.getText());
           double c = Double.parseDouble(bil3.getText());
           hasil1 = a+b+c;
           hasil.setText(a + " + " + b +" + "+ c +" = " + hasil1 );
           }
           else if (jumbil.getSelectedItem().equals("4")){
           double a = Double.parseDouble(bil1.getText());
           double b = Double.parseDouble(bil2.getText());
           double c = Double.parseDouble(bil3.getText());
           double d = Double.parseDouble(bil4.getText());
           hasil1 = a+b+c+d;
           hasil.setText(a + " + " + b +" + "+ c +" + "+ d+" = " + hasil1 );
           }     
        }
           else if(jenarit.getSelectedItem().equals("Perkalian")){
           if (jumbil.getSelectedItem().equals("2")){
           double a = Double.parseDouble(bil1.getText());
           double b = Double.parseDouble(bil2.getText());
           hasil1 = a*b;
           hasil.setText(a + " x " + b + " = " + hasil1 );
           }
           else if (jumbil.getSelectedItem().equals("3")){
           double a = Double.parseDouble(bil1.getText());
           double b = Double.parseDouble(bil2.getText());
           double c = Double.parseDouble(bil3.getText());
           hasil1 = a*b*c;
           hasil.setText(a + " x " + b +" x "+ c +" = " + hasil1 );
           }
           else if (jumbil.getSelectedItem().equals("4")){
           double a = Double.parseDouble(bil1.getText());
           double b = Double.parseDouble(bil2.getText());
           double c = Double.parseDouble(bil3.getText());
           double d = Double.parseDouble(bil4.getText());
           hasil1 = a*b*c*d;
           hasil.setText(a + " x " + b +" x "+ c +" x "+ d+" = " + hasil1 );
           }     
        }
           else if(jenarit.getSelectedItem().equals("Pembagian")){
           if (jumbil.getSelectedItem().equals("2")){
           double a = Double.parseDouble(bil1.getText());
           double b = Double.parseDouble(bil2.getText());
           hasil1 = a/b;
           hasil.setText(a + " : " + b + " = " + hasil1 );
           }
           else if (jumbil.getSelectedItem().equals("3")){
           double a = Double.parseDouble(bil1.getText());
           double b = Double.parseDouble(bil2.getText());
           double c = Double.parseDouble(bil3.getText());
           hasil1 = a/b/c;
           hasil.setText(a + " : " + b +" : "+ c +" = " + hasil1 );
           }
           else if (jumbil.getSelectedItem().equals("4")){
           double a = Double.parseDouble(bil1.getText());
           double b = Double.parseDouble(bil2.getText());
           double c = Double.parseDouble(bil3.getText());
           double d = Double.parseDouble(bil4.getText());
           hasil1 = a/b/c/d;
           hasil.setText(a + " : " + b +" : "+ c +" : "+ d+" = " + hasil1 );
           }     
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bil1;
    private javax.swing.JTextField bil2;
    private javax.swing.JTextField bil3;
    private javax.swing.JTextField bil4;
    private javax.swing.JLabel bill1;
    private javax.swing.JLabel bill2;
    private javax.swing.JLabel bill3;
    private javax.swing.JLabel bill4;
    private javax.swing.JTextArea hasil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenarit;
    private javax.swing.JComboBox<String> jumbil;
    private javax.swing.JPanel ket;
    private javax.swing.JLabel kete;
    private javax.swing.JLabel keter;
    private javax.swing.JLabel label6;
    // End of variables declaration//GEN-END:variables
}
